export const PLUGIN_NAME = "openagent-labforge"
export const LEGACY_PLUGIN_NAME = "oh-my-opencode"
export const CONFIG_BASENAME = "openagent-labforge"
export const LEGACY_CONFIG_BASENAME = "oh-my-opencode"
export const LOG_FILENAME = "openagent-labforge.log"
export const CACHE_DIR_NAME = "openagent-labforge"
