import { z } from "zod"

export const BuiltinAgentNameSchema = z.enum([
  "sisyphus",
  "wase",
  "hephaestus",
  "prometheus",
  "oracle",
  "librarian",
  "explore",
  "github-scout",
  "tech-scout",
  "article-writer",
  "scientific-writer",
  "bio-orchestrator",
  "multimodal-looker",
  "bio-methodologist",
  "wet-lab-designer",
  "bio-pipeline-operator",
  "paper-evidence-synthesizer",
  "metis",
  "momus",
  "atlas",
])

export const BuiltinSkillNameSchema = z.enum([
  "playwright",
  "agent-browser",
  "dev-browser",
  "frontend-ui-ux",
  "git-master",
  "docx-workbench",
  "pdf-toolkit",
  "pptx-studio",
  "xlsx-analyst",
  "web-research",
  "data-analysis",
  "bio-tools",
  "bio-methods",
  "bio-visualization",
  "wet-lab-design",
  "bio-pipeline",
  "paper-evidence",
  "differential-expression",
  "scrna-preprocessing",
  "cell-annotation",
  "pubmed-search",
  "geo-query",
  "sequence-analysis",
  "structural-biology",
  "vector-design",
])

export const OverridableAgentNameSchema = z.enum([
  "build",
  "plan",
  "sisyphus",
  "wase",
  "hephaestus",
  "sisyphus-junior",
  "OpenCode-Builder",
  "prometheus",
  "metis",
  "momus",
  "oracle",
  "librarian",
  "explore",
  "github-scout",
  "tech-scout",
  "article-writer",
  "scientific-writer",
  "bio-orchestrator",
  "multimodal-looker",
  "bio-methodologist",
  "wet-lab-designer",
  "bio-pipeline-operator",
  "paper-evidence-synthesizer",
  "atlas",
])

export const AgentNameSchema = BuiltinAgentNameSchema
export type AgentName = z.infer<typeof AgentNameSchema>

export type BuiltinSkillName = z.infer<typeof BuiltinSkillNameSchema>
